# Generated by Django 4.0.3 on 2022-04-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Категории еды',
                'verbose_name_plural': 'Категории еды',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=255)),
                ('slag', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('kkal', models.IntegerField(max_length=4)),
                ('proteins', models.FloatField(max_length=6)),
                ('fats', models.FloatField(max_length=6)),
                ('carbohydrates', models.FloatField(max_length=6)),
                ('type_of_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_diary.type_of_food')),
            ],
        ),
    ]
