# Generated by Django 4.0.4 on 2022-04-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0002_alter_food_kkal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
    ]
