# Generated by Django 4.0.4 on 2022-04-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0003_alter_food_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_of_food',
            name='slag',
        ),
    ]
