# Generated by Django 4.0.4 on 2022-04-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0004_remove_type_of_food_slag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_of_food',
            name='photo',
        ),
    ]
