# Generated by Django 4.0.4 on 2022-04-28 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0005_remove_type_of_food_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='slag',
        ),
        migrations.AlterField(
            model_name='food',
            name='kkal',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2500)]),
        ),
    ]
