# Generated by Django 4.0.3 on 2022-05-05 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_merge_20220425_1936'),
        ('food_diary', '0006_remove_food_slag_alter_food_kkal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name_of_product'], 'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
        migrations.CreateModel(
            name='Diary_of_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_create', models.DateTimeField(auto_now_add=True)),
                ('grams', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000)])),
                ('consumed_kkal', models.FloatField(null=True)),
                ('consumed_proteins', models.FloatField(null=True)),
                ('consumed_fats', models.FloatField(null=True)),
                ('consumed_carbohydrates', models.FloatField(null=True)),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_diary.food')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.profile')),
            ],
            options={
                'verbose_name': 'Дневник питания',
                'verbose_name_plural': 'Дневник питания',
                'ordering': ['day_create'],
            },
        ),
    ]
