# Generated by Django 4.0.3 on 2022-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_diary', '0007_alter_food_options_diary_of_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary_of_food',
            name='day_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
