# Generated by Django 4.0.3 on 2022-05-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_profile_photo'),
        ('food_diary', '0008_alter_diary_of_food_day_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary_of_food',
            name='id_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.profile'),
        ),
    ]
