# Generated by Django 4.0.3 on 2022-04-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_about_user_age_alter_about_user_growth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_user',
            name='slag',
        ),
    ]
