# Generated by Django 4.0.3 on 2022-04-19 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0003_remove_about_user_slag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_user',
            new_name='Profile',
        ),
    ]
