# Generated by Django 4.0.4 on 2022-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rename_about_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='needed_carbohydrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='needed_fats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='needed_kkal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='needed_proteins',
            field=models.IntegerField(null=True),
        ),
    ]
