# Generated by Django 4.0.3 on 2022-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rename_about_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_profile/%Y/%m/%d'),
        ),
    ]
