# Generated by Django 4.0.4 on 2022-04-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_profile_needed_carbohydrates_and_more'),
        ('calculator', '0005_profile_photo'),
    ]

    operations = [
    ]
