# Generated by Django 4.0.3 on 2022-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_merge_20220425_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profile/%Y/%m/%d'),
        ),
    ]
