# Generated by Django 4.0.3 on 2022-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='iconForPersonalarea.png', null=True, upload_to='photos_profile/%Y/%m/%d'),
        ),
    ]
