version: "3.9"
services:
  app:
    build: healthyfitness
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_contaner
    command: python manage.py runserver 0.0.0.0:8000
