# Generated by Django 4.0.3 on 2022-05-27 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_training', models.CharField(max_length=255)),
                ('kkal_in_hour', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2500)])),
            ],
            options={
                'verbose_name': 'Виды тренировок',
                'verbose_name_plural': 'Виды тренировок',
                'ordering': ['type_training'],
            },
        ),
        migrations.CreateModel(
            name='Training_trecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_create', models.DateField(auto_now_add=True)),
                ('duration_training_min', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1440)])),
                ('burned_kkal', models.FloatField(null=True)),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sport.type_of_training')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.profile')),
            ],
            options={
                'verbose_name': 'Трекер тренировок',
                'verbose_name_plural': 'Трекер тренировок',
                'ordering': ['day_create', 'id'],
            },
        ),
    ]
