# Generated by Django 4.0.3 on 2022-05-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_trecker',
            old_name='id_food',
            new_name='id_training',
        ),
    ]
