# Generated by Django 4.0.3 on 2022-05-06 12:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0008_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_create', models.DateField(auto_now_add=True)),
                ('number_of_glasses', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)])),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.profile')),
            ],
            options={
                'verbose_name': 'Трекер воды',
                'verbose_name_plural': 'Трекер воды',
                'ordering': ['day_create'],
            },
        ),
    ]
